### ISSUE TITLE
两个小错误，谢谢你的笔记。

### ISSUE THREAD

**Issue by chenshijin1** [Relph1119/StatisticalLearningMethod-Camp#1]
P5 泛化误差上界
[错误一](http://note.youdao.com/noteshare?id=8532c2514cff38fd39e785b972a0a253&sub=F79D8A61728445A3A43C2D36EB2A00B3)
P29 决策树的生成
[错误二](http://note.youdao.com/noteshare?id=9747a8e0147696adb0e12f39280fd662&sub=A65431AF2CD447129FCB114D88381957)
添加的错误
P40 拉格朗日对偶性
[错误三](http://note.youdao.com/noteshare?id=292dcd296221eac010cb806e9f7ce689&sub=82E178504029405BB4D86D79E42A7094)
P52 支持向量机这一章节，从P52开始，内容发生了混乱和重复
[错误四](http://note.youdao.com/noteshare?id=598afdb864563ddf1036524f6e7bcc16&sub=A3B7E294AAE14ABCA80C58D38CD8DEF3)

**Comment by Relph1119** [comment]
已修改完成
